version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1

    steps:
      - checkout
      
      - run:
          name: check directory
          command: ls
      - run:
          name: install node_modules
          command: cd client/app;npm install;
      
      - run:
          name: testing
          command: cd client/app;npm test --watchAll=false
      
      - run:
          name: npm build
          command: cd client/app;npm build
      
      - run:
          name: deploy
          command: bash client_deploy.sh
