version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1

    steps:
      - checkout
      
      - add_ssh_keys:
          fingerprints:
            - "d3:59:eb:87:e6:6a:41:af:6b:66:83:cf:c8:a4:49:6b"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/app/package.json" }}
            - v1-dependencies
      
      - run:
          name: install node_modules
          command: cd client/app;npm install;
      
      - save_cache:
          paths:
            - client/app/node_modules
          key: v1-dependencies-{{ "client/app/package.json" }}

      - run:
          name: testing
          command: cd client/app;npm test --watchAll=false
      
      - run:
          name: npm build
          command: unset CI;cd client/app;npm run build
            
      - run:
          name: deploy
          command: bash circleci.client_deploy.sh
