version: "3"

services:
  db:
    container_name: db
    build:
      context: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_ID}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db/data:/backup

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - 80:80
      - 443:443
    expose:
      - '80'
      - '443'
    volumes:
      - ./gateway/dev/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apiserver
      - authserver
      - fileserver
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  apiserver:
    container_name: apiserver
    build:
      context: ./api
    ports:
      - 8003:8003
    environment:
      NODE_ENV: "development"
      DB_ID: "${DB_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
      FILE_USER: "${FILE_USER}"
      FILE_PASSWORD: "${FILE_PASSWORD}"
    volumes:
      - ./api/app:/usr/app
    command: 'npm start'

  authserver:
    container_name: authserver
    build:
      context: ./auth
    ports:
      - 8001:8001
    environment:
      NODE_ENV: development
      DB_ID: "${DB_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
    volumes:
      - ./auth/app:/usr/app
    command: 'npm start'

  fileserver:
    container_name: fileserver
    build:
      context: ./file
    environment:
      FTP_USER: "${FILE_USER}"
      FTP_PASS: "${FILE_PASSWORD}"
      PASV_ADDRESS: "5.6.7.8"
      PASV_MIN: 21100
      PASV_MAX: 21110
    ports:
      - 21:21
      - 21100-21110:21100-21110
    volumes:
      - ./file/backup:/home
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 5050:80