version: "3"

services:
  db:
    container_name: db
    build:
      context: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_ID}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db/data:/backup

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - 80:80
      - 443:443
    expose:
      - '80'
      - '443'
    restart: always
    volumes:
      - ./gateway/app/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/data/certbot/www:/var/www/certbot
      - ./gateway/data/certbot/conf:/etc/letsencrypt
    depends_on:
      - apiserver
      - authserver
      - fileserver
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./gateway/data/certbot/conf:/etc/letsencrypt
      - ./gateway/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  apiserver:
    container_name: apiserver
    build:
      context: ./api
    ports:
      - 8003:8003
    environment:
      NODE_ENV: "product"
      DB_ID: "${DB_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
      FILE_USER: "${FILE_USER}"
      FILE_PASSWORD: "${FILE_PASSWORD}"
      BASEURL: "${BASEURL}"
    volumes:
      - ./api/app:/usr/app
      - /usr/app/node_modules
    command: 'npm run build'

  authserver:
    container_name: authserver
    build:
      context: ./auth
    ports:
      - 8001:8001
    environment:
      NODE_ENV: "product"
      DB_ID: "${DB_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
    volumes:
      - ./auth/app:/usr/app
      - /usr/app/node_modules
    command: 'npm run build'

  fileserver:
    container_name: fileserver
    build:
      context: ./file
    environment:
      FTP_USER: "${FILE_USER}"
      FTP_PASS: "${FILE_PASSWORD}"
      PASV_ADDRESS: "5.6.7.8"
      PASV_MIN: 21100
      PASV_MAX: 21110
    ports:
      - 21:21
      - 21100-21110:21100-21110
    volumes:
      - ./file/backup:/home
